In [ ]:
print("hello")

hello

In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("Sources\ech_annonces_locations_68.csv", on_bad_lines="skip", sep=";")
df.head()

<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
C:\Users\J1141753\AppData\Local\Temp\ipykernel_36492\1575699831.py:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
  df = pd.read_csv("Sources\ech_annonces_locations_68.csv", on_bad_lines="skip", sep=";")

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,date,INSEE_COM,IRIS,CODE_IRIS,TYP_IRIS_x,TYP_IRIS_y,GRD_QUART,UU2010,REG,DEP
0,immo-facile-52417007,pr,m,l,0,116,NaN,5,1250,NaN,...,2023-04,68159,0,681590000,Z,Z,6815900,68000,44,68
1,ag672097-382986683,pr,a,l,3,44,NaN,3,600,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
2,ag672097-383464082,pr,a,l,1,53,NaN,2,498,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
3,ag680864-383044166,pr,a,l,0,41,NaN,2,460,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
4,ag672097-380998252,pr,a,l,2,74,NaN,4,695,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68

In [6]:
df.describe()

,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,prix_terrain,mensualiteFinance,balcon,eau,...,nb_logements_copro,charges_copro,duree_int,INSEE_COM,IRIS,CODE_IRIS,GRD_QUART,UU2010,REG,DEP
count,11702.000000,11702.000000,507.000000,11702.000000,11702.000000,0.0,0.0,11702.0,11702.000000,11702.000000,...,9.000000,0.0,11448.000000,11702.000000,11702.000000,1.170200e+04,1.170200e+04,11702.000000,11702.000000,11702.000000
mean,1.840711,65.150060,564.100118,2.820629,714.543924,NaN,NaN,0.0,0.186977,0.286789,...,18.666667,NaN,-207.466632,68191.909844,244.231499,6.819193e+08,6.819192e+06,68324.462400,44.018886,67.999316
std,24.546138,30.798055,776.823114,1.219675,286.924335,NaN,NaN,0.0,0.459904,0.465137,...,42.272923,NaN,422.747918,814.069476,385.032725,8.140732e+06,8.140730e+04,3166.426849,1.763585,0.807832
min,-2.000000,7.000000,1.710000,1.000000,1.000000,NaN,NaN,0.0,0.000000,0.000000,...,0.000000,NaN,-1125.000000,6088.000000,0.000000,6.088010e+07,6.088010e+05,758.000000,11.000000,6.000000
25%,0.000000,45.000000,200.000000,2.000000,531.000000,NaN,NaN,0.0,0.000000,0.000000,...,3.000000,NaN,-757.000000,68093.000000,0.000000,6.809300e+08,6.809300e+06,68402.000000,44.000000,68.000000
50%,1.000000,62.000000,455.000000,3.000000,660.000000,NaN,NaN,0.0,0.000000,0.000000,...,5.000000,NaN,15.000000,68224.000000,103.000000,6.822402e+08,6.822401e+06,68501.000000,44.000000,68.000000
75%,2.000000,79.000000,700.000000,3.000000,820.000000,NaN,NaN,0.0,0.000000,1.000000,...,8.000000,NaN,41.000000,68271.000000,202.000000,6.827101e+08,6.827101e+06,68701.000000,44.000000,68.000000
max,999.000000,450.000000,10198.000000,13.000000,3287.000000,NaN,NaN,0.0,12.000000,3.000000,...,131.000000,NaN,504.000000,86214.000000,6220.000000,8.621401e+08,8.621401e+06,86601.000000,93.000000,86.000000

In [1]:
df['etage'].max()

NameError: name 'df' is not defined