In [1]:
import numpy as np
import pandas as pd

In [2]:
df_locations = pd.read_csv("Sources\ech_annonces_locations_68.csv", on_bad_lines="skip", sep=";")
df_locations.head()

<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
C:\Users\J1141753\AppData\Local\Temp\ipykernel_36300\2403218379.py:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
  df_locations = pd.read_csv("Sources\ech_annonces_locations_68.csv", on_bad_lines="skip", sep=";")

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,date,INSEE_COM,IRIS,CODE_IRIS,TYP_IRIS_x,TYP_IRIS_y,GRD_QUART,UU2010,REG,DEP
0,immo-facile-52417007,pr,m,l,0,116,NaN,5,1250,NaN,...,2023-04,68159,0,681590000,Z,Z,6815900,68000,44,68
1,ag672097-382986683,pr,a,l,3,44,NaN,3,600,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
2,ag672097-383464082,pr,a,l,1,53,NaN,2,498,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
3,ag680864-383044166,pr,a,l,0,41,NaN,2,460,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
4,ag672097-380998252,pr,a,l,2,74,NaN,4,695,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68

In [3]:
df_ventes = pd.read_csv("Sources\ech_annonces_ventes_68.csv", sep=";")
df_ventes.head()

<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
C:\Users\J1141753\AppData\Local\Temp\ipykernel_36300\2465554355.py:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
  df_ventes = pd.read_csv("Sources\ech_annonces_ventes_68.csv", sep=";")

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,hektor-robischung-2862,pr,a,v,0,64,NaN,3,128400,NaN,...,68113,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2006.25
1,apimo-82452515,pr,m,v,0,85,4950.0,4,189000,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2223.53
2,immo-facile-52471952,pr,m,v,0,187,3182.0,9,282900,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,1512.83
3,immo-facile-52477215,pr,a,v,0,76,NaN,4,79000,NaN,...,68000,44,68,7.93,3.0,0.092,7.93,3.0,0.092,1039.47
4,ag681088-383601401,pr,m,v,0,90,3071.0,5,317000,NaN,...,68000,44,68,9.77,2.0,0.033,9.77,2.0,0.033,3522.22

In [4]:
df = pd.concat([df_locations, df_ventes], axis=0)
df.head()

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,immo-facile-52417007,pr,m,l,0,116,NaN,5,1250,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ag672097-382986683,pr,a,l,3,44,NaN,3,600,NaN,...,68701,44,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ag672097-383464082,pr,a,l,1,53,NaN,2,498,NaN,...,68701,44,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ag680864-383044166,pr,a,l,0,41,NaN,2,460,NaN,...,68701,44,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ag672097-380998252,pr,a,l,2,74,NaN,4,695,NaN,...,68701,44,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df['etage'] = df['etage'].replace([999, 99], df['etage'].median())
df['etage'].value_counts()

etage
 0     25555
 1      5126
 2      4276
 3      2405
 4      1081
 5       400
 6       166
 7        85
 10       76
 8        57
 9        42
 15       40
 12       27
 11       27
 14       17
 13       16
-1        13
 16        8
 22        7
 17        5
-2         2
 19        2
 18        2
 24        1
 26        1
 20        1
 21        1
Name: count, dtype: int64

In [9]:
df.loc[(df['parking'].isna()) & (df['places_parking'].notna()), 'parking'] = True